Repository roskakori/pygount, pull requests merged in 2020-03, with the labels that each got.

#25 Fix for folders_to_skip and names_to_skip
  pygount/analysis.py
  pygount/command.py
Labels: bug

#27 #26 Fixed test case for IDL Lexer
  .pre-commit-config.yaml
  .travis.yml
  dev-requirements.txt
  pygount/analysis.py
  pygount/command.py
  setup.py
  tests/test_lexers.py
Labels: cleanup

#28 #26 Updated requirements to current versions.
  .gitignore
  .travis.yml
  dev-requirements.txt
  setup.cfg
  tox.ini
Labels: cleanup

#29 Added option --format=summary
  .gitignore
  .travis.yml
  README.rst
  pygount/analysis.py
  pygount/command.py
  pygount/common.py
  pygount/write.py
  tests/_common.py
  tests/test_command.py
  tests/test_write.py
Labels: enhancement

#31 #30 Updated copyright year.
  LICENSE.txt
  pygount/__init__.py
  pygount/analysis.py
  pygount/command.py
  pygount/common.py
  pygount/lexers.py
  pygount/write.py
  pygount/xmldialect.py
  setup.py
  tests/test_analysis.py
  tests/test_command.py
  tests/test_common.py
  tests/test_lexers.py
  tests/test_write.py
  tests/test_xmldialect.py
Labels: cleanup

#32 #16 Fixed display of documentation count and percentage in summary.
  pygount/write.py
  tests/test_write.py
Labels: bug

#34 #16 Improved summary
  README.rst
  pygount/write.py
  tests/test_write.py
Labels: bug

#39 Added GitHub actions
  .github/workflows/build.yml
  .travis.yml
  README.md
Labels: cleanup

#40 #38 Fixed workflow name.
  README.md
Labels: cleanup

#41 Cleaned up project, part 2
  .github/workflows/build.yml
  CHANGES.md
  CONTRIBUTING.md
  README.md
  dev-requirements.txt
  setup.py
  tests/__init__.py
  tests/_common.py
  tests/count_pygount.sh
  tests/test_analysis.py
  tests/test_command.py
  tests/test_write.py
  tests/test_xmldialect.py
  tox.ini
Labels: cleanup

#42 Cleaned up project, part 3
  build.xml
Labels: cleanup

#43 #37 Added file count to summary
  CHANGES.md
  CONTRIBUTING.md
  pygount/__init__.py
  pygount/analysis.py
  pygount/summary.py
  pygount/write.py
  tests/test_analysis.py
  tests/test_summary.py
  tests/test_write.py
Labels: enhancement

#45 Moved documentation to ReadTheDocs, part 1
  .github/workflows/build.yml
  .gitignore
  docs/Makefile
  docs/_static/.keep
  docs/_templates/.keep
  docs/api.rst
  docs/background.rst
  docs/changes.rst
  docs/conf.py
  docs/continuous-integration.rst
  docs/contributing.rst
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  docs/usage.rst
  pygount/analysis.py
  readthedocs.yml
Labels: cleanup
